spring.application.name: sendzy
spring.profiles.active: local

spring:
  config:
    import:
      - db-core.yml

mybatis:
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:mybatis-config.xml

server:
  servlet:
    session:
      timeout: 20m
      cookie:
        http-only: true
        secure: true
