---
spring.config.activate.on-profile: local

spring:
  datasource:
    url: jdbc:h2:file:./data/sendzy;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
